#!/bin/sh
#
# Brian Freeman 
# run - Script to setup lib path and the run adviewer.gui.ADWindow.java 
# November 14, 2015
#
########################################################################s

# library path
LP=$(pwd)"/lib"
echo "lib path = ${LP}"

#src folder
SRC=$(pwd)"/src"

#where class files are
BIN=$(pwd)"/bin"

#temp for building class path
temp=""

#loop through library files and add .jars to class path
for jar in `ls $LP| grep .jar `
do
	temp="${LP}/${jar}:${temp}"
done

temp="${temp}:."

#print temp for debuging
echo "class files =${temp}"

#pass dir to ADWindow.java so the java file knows where it is executed from.
dir=`pwd` 

#switch to bin directory...
cd $BIN

#execute java
echo "executing java ...... "
java -cp $temp adviewer.gui.ADWindow -d "${dir}" "$@"
